apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'api'
  labels:
    role: api
spec:
  selector:
    matchLabels:
      role: api
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
        - name: api
          image: hello-world:v2
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 3
            initialDelaySeconds: 5
            failureThreshold: 2
            successThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: 'api'
  labels:
    role: api
spec:
  ports:
  - port: 8081
    targetPort: 80
    protocol: TCP
  selector:
    role: api
  type: LoadBalancer
---
